---
title: "Midterm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(stringr)
library(dplyr)
```

```{r}
nba <- read_csv("./NBA_player_of_the_week.csv")
```

```{r}
nba <- nba %>%
  mutate(new_date = as.Date(Date, 'Apr 14, 1985',format='%b %d, %Y'),
         year = as.numeric(str_sub(new_date, start = 1, end = 4)),
         month = as.numeric(str_sub(new_date, start = 6, end = 7)),
         day = as.numeric(str_sub(new_date, start = 9, end = 10)), 
         date_time = make_datetime(year = year, month = month, day = day,
                                   hour = 0L, min = 0L, sec = 0)) %>%
  mutate(new_height = as.numeric(str_remove_all(Height, pattern = "cm"))*0.393701) %>%
  mutate(new_height0 = as.numeric(str_remove_all(Height, pattern = "-")),
         new_height1 = (as.numeric(str_sub(new_height0, start = 1, end = 1))*12),
         new_height2 = (as.numeric(str_sub(new_height0, start = 2, end = 3))),
         new_height0 = new_height1 + new_height2,
         height_inch = coalesce(new_height,new_height0))

```

