---
title: "R Workshop - Practice Exercises - 1.2"
output:
  html_document: default
  pdf_document: default
---
## Setup

```{r}
library(tidyverse)
update.packages("tidyr")
```


## The Data

```{r read_data}
cereals <- read_csv("https://www.dropbox.com/s/ll2c9drmlom1ony/cereals.csv?dl=1")
```

Documentation for dataset: https://www.kaggle.com/crawford/80-cereals/version/2

```{r check_data, eval = FALSE}
#### Edit this code to examine your dataset
str()
summary()
```


[Briefly summarize the dataset here.]

[CHECKPOINT:  Knit your Markdown file!]

## Data Cleaning and Transformation


```{r summarize}
#### Write code to show the mean and median and sd of sugar content per serving of all cereals
```

```{r summarize2}
#### Write code to show the total calories of all cereals
```


```{r mutate}
#### Write code to create the variable "cal_per_cup" here
```

```{r filter_select}
#### Write code to include only Kellogg brand cereals, and only relevant columns
```


```{r arrange}
#### Write code to sort the dataset by calories per cup
iris %>%
 pivot_longer(Sepal.Length:Petal.Width,
              names_to = "Flower.Part",
              values_to = "Size") %>%
 ggplot(aes(x = Flower.Part, y = Size)) +
 geom_boxplot()

```


[CHECKPOINT: Knit your document!]

## Visualizing the data
```{r}
library(lubridate)
bday <- ("November 21, 1998")
mein2020 <- bday + years(22)
wday(mein2020)
```


## Conclusion

What did you learn about cereals?  Write a few sentences summarizing your findings, knit your document, and admire your handiwork!

```{r}
colleges_clean <- read_csv("./colleges_clean.csv")

colleges_clean %>%
  group_by(STABBR) %>%
  summarize(
    avg_state_tuition = mean(TUITIONFEE_OUT)
  ) %>%
  mutate(
    STABBR = fct_reorder(STABBR, avg_state_tuition)
  ) %>%
  ggplot() +
  geom_col(aes(x = STABBR, y = avg_state_tuition))



colleges_clean %>%
count(REGION, STABBR) %>%
  mutate(REGION = factor(REGION)) %>%
  REGION = fct_recode(REGION,
                      MilitaryAcademies = "0",
                      NorthEast = "1", 
                      EastCoast = "2", 
                      MidWest = "3", 
                      Mid = "4", 
                      SouthEast = "5",
                      SouthWest = "6",
                      MountainWest = "7",
                      WestCoast = "8",
                      Territories = "9")))

summary(colleges_clean2$REGION)

str_match(colleges_clean$INSTNM, "Poly")



colleges_clean %>% 
  select(INSTNM) %>% filter(str_detect(INSTNM, 'Poly'))


colleges_clean %>% 
  pull(INSTNM) %>% 
  str_detect("University") %>%
  sum()

  
```

```{r}
my_vector <- c("hey, my name is Rachie", "taco bell", "Rachie")

str_detect(my_vector, "Rachie")
str_extract(my_vector, "Rachie")
length(my_vector)
my_vec <- c("a", "b", "apple a", "banana")
my_vec %>%
  str_replace_all("a", "u")
my_vec%>%
  str_extract_all("a")
```

